github worlflow 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,15 +28,20 @@ jobs:
             - name: Install dependencies
               run: bun install
             - name: Build
-              run: bun run build
+              run: |
+                  tsc && vite build
+                  if [ ! -f "./dist/index.html" ]; then
+                    echo "index.html not found"
+                    exit 1
+                  fi
             - name: Install Headless Chrome
               run: |
                   sudo apt-get update
                   sudo apt-get install -y chromium-browser
             - name: Install React Snap
-              run: npm install react-snap --save-dev
+              run: bun add react-snap --save-dev
             - name: Run React Snap
-              run: npm run postbuild
+              run: bun run postbuild
               env:
                   CI: true
             - name: Setup Pages
